services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    networks:
      - jaryan-network

#  scylla-1:
#    image: scylladb/scylla
#    container_name: scylla-1
#    hostname: scylla-1
#    command: --reactor-backend=epoll --smp 2 --memory 2G
#    networks:
#      - jaryan-network
#    ports:
#      - "9042:9042"
#    restart: unless-stopped
#
#  scylla-2:
#    image: scylladb/scylla
#    container_name: scylla-2
#    hostname: scylla-2
#    command: --reactor-backend=epoll --seeds=scylla-1 --smp 2 --memory 2G
#    networks:
#      - jaryan-network
#    restart: unless-stopped
#
#  scylla-3:
#    image: scylladb/scylla
#    container_name: scylla-3
#    hostname: scylla-3
#    command: --reactor-backend=epoll --seeds=scylla-1 --smp 2 --memory 2G
#    networks:
#      - jaryan-network
#    restart: unless-stopped

  minio:
    image: quay.io/minio/minio
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: username
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    networks:
      - jaryan-network
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: jaryan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p
    volumes:
      - postgres-vol:/var/lib/postgresql
    networks:
      - jaryan-network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - jaryan-network
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-vol:/data/db
    networks:
      - jaryan-network
    restart: unless-stopped

  livekit-server:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    hostname: livekit-server
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    volumes:
      - ./livekit-server-config.yaml:/etc/livekit-server-config.yaml
    command: --config /etc/livekit-server-config.yaml
    depends_on:
      - redis
    networks:
      - jaryan-network
    restart: unless-stopped

  livekit-egress:
    image: livekit/egress:latest
    container_name: livekit-egress
    hostname: livekit-egress
    ports:
      - "8080:8080"
    volumes:
      - ./egress-config.yaml:/out/config.yaml
      - ./recordings:/out/recordings
    environment:
      EGRESS_CONFIG_FILE: /out/config.yaml
    depends_on:
      - redis
      - livekit-server
      - minio
    networks:
      - jaryan-network
    restart: unless-stopped

networks:
  jaryan-network:
    name: jaryan-network

volumes:
  postgres-vol:
  mongo-vol:

